CREATE TABLE [dbo].[Categories]
(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(250) NOT NULL,
	IsPublished bit DEFAULT(0) NOT NULL,
	CreatedOn DATETIME2 DEFAULT(GETDATE()) NOT NULL,
	LastModified DATETIME2 NULL,
	PublishedOn DATETIME2 NULL
)
