CREATE TABLE [dbo].[Tags]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	AuthorId INT NOT NULL,
	TagName NVARCHAR(50) NOT NULL,
	CreatedOn DATETIME2 DEFAULT(GETDATE()) NOT NULL,
	LastModified DATETIME2 NULL,
	CONSTRAINT FK_Tags_People_AuthorId FOREIGN KEY (AuthorId) REFERENCES dbo.People(Id)
)
